### ISSUE TITLE
I own this exact Kindle, but it's on 5.6.0.1. or whatever the newest update it , will this still work?

### ISSUE THREAD

**Issue by Multimegamander** [d0k3/OneClick-for-Amazon-Fire#2]

**Comment by d0k3** [comment]
It won't work fully, cause Amazon patched a few of the requried commands. Running the script according to the instructions won't do any harm, though, so just do it if you want. You'll get a lot of errors, just ignore them.

What doesn't work:
* Disabling OTAs
* Disabling lockscreen ads natively
* Debloating

What does work:
* Installing Play Store and Play Services
* DNS based adblocker (may also get rid of lockscreen ads, unsure)
* Nova Launcher as default
