### ISSUE TITLE
Google Child's Device and Family Link

### ISSUE THREAD

**Issue by xSijil** [d0k3/OneClick-for-Amazon-Fire#3]
I am having trouble setting up the device as a child's device via Google accounts. After creating the primary (child's) account you're prompted to link a parental account using Google's Family Link app. This is where I run into an issue. When the app is almost done installing on the OneClicked Fire it fails due to "device settings". The error pop-up only stayed on screen for a second before closing itself and starting over the Google account sign in for setting up the play store and whatnot. Any suggestions or help would be great.

**Comment by d0k3** [comment]
So, what FW version is your Fire 7 on?

**Comment by d0k3** [comment]
Closing this, assuming it resolved.
