### ISSUE TITLE
Does this work for Nova Launcher and Google Play? (Fire 7 Gen 9)

### ISSUE THREAD

**Issue by FlameKat53** [d0k3/OneClick-for-Amazon-Fire#4]
I'm thinking of purchasing said device, and I don't like amazon launcher. Pixel Launcher would also be nice if it works on any Fire.

**Comment by vRobM** [comment]
You can pick the launcher.
I'd suggest getting a better faster device than the pokey 7.

**Comment by d0k3** [comment]
There's only one way to find out, and that's trying it yourself. My best guess is, it won't work. Amazon works hard to lock these devices down more and more with each update.

Better get a 7. gen device (with no updates, that's important) and follow the instructions on XDA to install LineageOS. Anyways, this is no discussion forum, so I'm closing this now.

**Comment by FlameKat53** [comment]
Ah, I’ll look for such device. And apologies for the questions here and not on an IRC or such (I do not know of one) 😛
